//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApITest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Livre
    {
        public int id { get; set; }
        public string nom { get; set; }
        public Nullable<int> code { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<int> reviews { get; set; }
        public string description { get; set; }
        public string imgUrl { get; set; }
        public string categorie { get; set; }
    }
}
